service:
  name: feature-engineering-service
  version: "2.0.0"
  description: "Generate 110 ML features from aggregates"

clickhouse:
  host: suho-clickhouse
  port: 8123
  database: suho_analytics
  username: suho_analytics
  password: clickhouse_secure_2024

processing:
  poll_interval: 60  # seconds
  batch_size: 1000
  calculate_targets: true  # Set false for live data

  # Timeframe mapping for multi-timeframe features
  timeframe_mapping:
    5m:
      higher: 15m
      lower: 1m
    15m:
      higher: 1h
      lower: 5m
    30m:
      higher: 1h
      lower: 15m
    1h:
      higher: 4h
      lower: 15m
    4h:
      higher: 1d
      lower: 1h
    1d:
      higher: 1w
      lower: 4h
    1w:
      higher: null
      lower: 1d
