# Central Hub Service - Docker Compose
# Phase 1 Infrastructure Migration

version: '3.8'

services:
  central-hub:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    environment:
      - CENTRAL_HUB_SERVICE_NAME=central-hub
      - CENTRAL_HUB_SERVICE_PORT=8010
      - CENTRAL_HUB_SERVICE_HOST=0.0.0.0
      - CENTRAL_HUB_LOG_LEVEL=INFO
      - CENTRAL_HUB_LOG_FILE=logs/central-hub.log
      - CENTRAL_HUB_ENVIRONMENT=development
      - CENTRAL_HUB_DEBUG=false
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - central-hub-network

networks:
  central-hub-network:
    driver: bridge
    name: central-hub-network

volumes:
  central-hub-logs:
    name: central-hub-logs
  central-hub-config:
    name: central-hub-config