/**
 * central-hub Configuration
 * Generated by Service Port Coordinator
 */

module.exports = {
    service: {
        name: 'central-hub',
        port: 7000,
        protocol: 'http',
        description: 'Service Discovery & Registration Hub',
        critical: true
    },

    server: {
        host: process.env.SERVICE_HOST || 'localhost',
        port: process.env.PORT || 7000,
        timeout: 30000
    },

    centralHub: {
        url: process.env.CENTRAL_HUB_URL || 'http://localhost:7000',
        registerOnStart: true,
        heartbeatInterval: 30000
    },

    health: {
        endpoint: '/health',
        interval: 15000
    },

    security: {
        corsEnabled: true,
        rateLimitEnabled: true,
        helmetEnabled: true
    },

    monitoring: {
        metricsEnabled: true,
        loggingEnabled: true,
        performanceTracking: true
    }
};