# Central Hub Service - Main Configuration
# Phase 1 Infrastructure Migration

service:
  name: "central-hub"
  description: "Central service orchestration and coordination hub"
  version: "1.0.0"
  phase: "Phase 1 - Infrastructure Migration"

logging:
  level: "INFO"
  format: "json"
  file: "logs/central-hub.log"
  max_file_size: "10MB"
  backup_count: 5

registry:
  ttl: 300  # 5 minutes
  cleanup_interval: 60  # 1 minute
  enable_auto_cleanup: true

health:
  check_interval: 30  # seconds
  timeout: 10  # seconds
  enable_system_monitoring: true
  thresholds:
    cpu:
      warning: 70.0
      critical: 90.0
    memory:
      warning: 80.0
      critical: 95.0
    disk:
      warning: 85.0
      critical: 95.0

api:
  cors:
    allow_origins: ["*"]
    allow_credentials: true
    allow_methods: ["*"]
    allow_headers: ["*"]
  rate_limiting:
    enabled: false  # Phase 1: basic implementation
    requests_per_minute: 60

features:
  phase1_focus:
    - "service_orchestration"
    - "service_registry"
    - "health_monitoring"
    - "configuration_management"
    - "basic_logging"

  excluded_from_phase1:
    - "ai_ml_features"
    - "advanced_analytics"
    - "complex_retention"
    - "telegram_integration"
    - "backtesting"

monitoring:
  metrics_enabled: true
  performance_tracking: true
  error_tracking: true