version: '3.8'

services:
  mql5-historical-scraper:
    build:
      context: .
      dockerfile: Dockerfile.historical
    container_name: mql5-historical-scraper
    environment:
      - ZAI_API_KEY=${ZAI_API_KEY:-2d6f4aef9cbf429b81684dc83c7dad9d.6OdXF8oPxTqbmGuJ}
      - DB_CONNECTION=${DB_CONNECTION:-}
      - PYTHONUNBUFFERED=1
    volumes:
      # Persist tracking data
      - ./data:/app/data
      - ./logs:/app/logs
    command: tail -f /dev/null
    restart: unless-stopped
    networks:
      - aitrading-network

networks:
  aitrading-network:
    external: true
