service:
  name: database-service
  description: Database Service microservice - Multi-database management with PostgreSQL, ClickHouse, Weaviate, ArangoDB
  version: 1.0.0
  environment: ${MICROSERVICE_ENVIRONMENT:development}
  port: ${DATABASE_SERVICE_PORT:8008}
  debug: ${DATABASE_SERVICE_DEBUG:false}
  host: ${DATABASE_SERVICE_HOST:0.0.0.0}
  
cors:
  enabled: ${CORS_ENABLED:true}
  origins:
    - ${CORS_ORIGINS:*}
    
rate_limiting:
  enabled: ${RATE_LIMITING_ENABLED:true}
  requests_per_minute: ${RATE_LIMITING_REQUESTS_PER_MINUTE:5000}  # High for database operations

authentication:
  enabled: ${AUTH_ENABLED:false}
  jwt_secret: ${JWT_SECRET_KEY:}
  jwt_algorithm: ${JWT_ALGORITHM:HS256}
  token_expire_minutes: ${JWT_TOKEN_EXPIRE_MINUTES:60}
  api_key_authentication: ${API_KEY_AUTH_ENABLED:true}

databases:
  postgresql:
    enabled: ${POSTGRESQL_ENABLED:true}
    host: ${POSTGRESQL_HOST:localhost}
    port: ${POSTGRESQL_PORT:5432}
    database: ${POSTGRESQL_DATABASE:main_db}
    user: ${POSTGRESQL_USER:postgres}
    password: ${POSTGRESQL_PASSWORD:}
    connection_pool:
      max_connections: ${POSTGRESQL_MAX_CONNECTIONS:50}
      min_connections: ${POSTGRESQL_MIN_CONNECTIONS:10}
    query_timeout: ${POSTGRESQL_QUERY_TIMEOUT:30}
    
  clickhouse:
    enabled: ${CLICKHOUSE_ENABLED:true}
    host: ${CLICKHOUSE_HOST:localhost}
    port: ${CLICKHOUSE_PORT:8123}
    database: ${CLICKHOUSE_DATABASE:analytics_db}
    user: ${CLICKHOUSE_USER:default}
    password: ${CLICKHOUSE_PASSWORD:}
    connection_pool:
      max_connections: ${CLICKHOUSE_MAX_CONNECTIONS:20}
      min_connections: ${CLICKHOUSE_MIN_CONNECTIONS:5}
    query_timeout: ${CLICKHOUSE_QUERY_TIMEOUT:60}
    
  weaviate:
    enabled: ${WEAVIATE_ENABLED:true}
    host: ${WEAVIATE_HOST:localhost}
    port: ${WEAVIATE_PORT:8080}
    api_key: ${WEAVIATE_API_KEY:}
    vector_dimensions: ${WEAVIATE_VECTOR_DIMENSIONS:1536}
    similarity_threshold: ${WEAVIATE_SIMILARITY_THRESHOLD:0.7}
    
  arangodb:
    enabled: ${ARANGODB_ENABLED:true}
    host: ${ARANGODB_HOST:localhost}
    port: ${ARANGODB_PORT:8529}
    database: ${ARANGODB_DATABASE:graph_db}
    user: ${ARANGODB_USER:root}
    password: ${ARANGODB_PASSWORD:}
    graph_collections: ${ARANGODB_GRAPH_COLLECTIONS:users,projects,workflows}
    
  dragonflydb:
    enabled: ${DRAGONFLYDB_ENABLED:true}
    host: ${DRAGONFLYDB_HOST:localhost}
    port: ${DRAGONFLYDB_PORT:6379}
    password: ${DRAGONFLYDB_PASSWORD:}
    cache_ttl_seconds: ${DRAGONFLYDB_CACHE_TTL_SECONDS:3600}
    max_memory_mb: ${DRAGONFLYDB_MAX_MEMORY_MB:2048}

schemas:
  auto_migration: ${SCHEMAS_AUTO_MIGRATION:true}
  backup_enabled: ${SCHEMAS_BACKUP_ENABLED:true}
  validation_enabled: ${SCHEMAS_VALIDATION_ENABLED:true}
  
performance:
  query_cache_enabled: ${PERFORMANCE_QUERY_CACHE_ENABLED:true}
  query_cache_ttl_seconds: ${PERFORMANCE_QUERY_CACHE_TTL_SECONDS:300}
  connection_timeout_seconds: ${PERFORMANCE_CONNECTION_TIMEOUT_SECONDS:30}
  bulk_insert_batch_size: ${PERFORMANCE_BULK_INSERT_BATCH_SIZE:1000}
  
monitoring:
  slow_query_threshold_ms: ${MONITORING_SLOW_QUERY_THRESHOLD_MS:1000}
  connection_monitoring: ${MONITORING_CONNECTION_MONITORING:true}
  performance_logging: ${MONITORING_PERFORMANCE_LOGGING:true}
  health_check_interval_seconds: ${HEALTH_CHECK_INTERVAL:30}
  metrics_enabled: ${METRICS_ENABLED:true}

logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  enable_query_logging: ${ENABLE_QUERY_LOGGING:true}
  enable_connection_logging: ${ENABLE_CONNECTION_LOGGING:true}

security:
  enable_authentication: ${ENABLE_AUTHENTICATION:false}
  api_key_header: ${API_KEY_HEADER:X-API-Key}
  allowed_ips: ${ALLOWED_IPS:}
  ssl_enabled: ${SSL_ENABLED:false}
  database_service_api_key: ${DATABASE_SERVICE_API_KEY:}
  service_secrets:
    api-gateway: ${API_GATEWAY_SERVICE_SECRET:}
    data-bridge: ${DATA_BRIDGE_SERVICE_SECRET:}
    trading-engine: ${TRADING_ENGINE_SERVICE_SECRET:}
    ai-orchestration: ${AI_ORCHESTRATION_SERVICE_SECRET:}
    ml-processing: ${ML_PROCESSING_SERVICE_SECRET:}

# Environment-specific configurations
environments:
  development:
    debug: true
    log_level: debug
    query_cache_enabled: false
    auto_migration: true
  production:
    debug: false
    log_level: info
    query_cache_enabled: true
    auto_migration: false
  testing:
    debug: true
    log_level: debug
    query_cache_enabled: false
    auto_migration: true