version: '3.8'

services:
  database-service:
    build: .
    ports:
      - "8008:8008"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=aitrading_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - CENTRAL_HUB_URL=http://central-hub:8000
    depends_on:
      - postgres
    volumes:
      - ./logs:/app/logs
    networks:
      - aitrading-network
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=aitrading_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - aitrading-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  aitrading-network:
    external: true