# Prometheus Configuration for AI Trading Platform
# Phase 1: Comprehensive Metrics Collection

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aitrading-platform'
    environment: 'development'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load alerting rules
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # System metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics

  # AI Trading Platform Services
  - job_name: 'central-hub'
    static_configs:
      - targets: ['central-hub:8010']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'database-service'
    static_configs:
      - targets: ['database-service:8008']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'data-bridge'
    static_configs:
      - targets: ['data-bridge:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'trading-engine'
    static_configs:
      - targets: ['trading-engine:8007']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'security-monitor'
    static_configs:
      - targets: ['security-monitor:8020']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  - job_name: 'log-aggregator'
    static_configs:
      - targets: ['log-aggregator:8030']
    scrape_interval: 15s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Database exporters
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  - job_name: 'clickhouse-exporter'
    static_configs:
      - targets: ['clickhouse-exporter:9116']
    scrape_interval: 30s

  # ClickHouse native metrics
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse-logs:9363']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics (if nginx-prometheus-exporter is used)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Weaviate metrics
  - job_name: 'weaviate'
    static_configs:
      - targets: ['weaviate:2112']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom application metrics with service discovery
  - job_name: 'aitrading-services'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 15s
        port: 8080
    relabel_configs:
      # Only target containers with the prometheus.io/scrape label
      - source_labels: [__meta_docker_container_label_prometheus_io_scrape]
        action: keep
        regex: true

      # Use custom port if specified
      - source_labels: [__meta_docker_container_label_prometheus_io_port]
        action: replace
        target_label: __address__
        regex: (.+)
        replacement: $1

      # Use custom metrics path if specified
      - source_labels: [__meta_docker_container_label_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)

      # Add container name as label
      - source_labels: [__meta_docker_container_name]
        action: replace
        target_label: container_name

      # Add service name from label
      - source_labels: [__meta_docker_container_label_service_name]
        action: replace
        target_label: service_name

  # Black box monitoring for external endpoints
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api-gateway:8000/health
        - http://central-hub:8010/health
        - http://database-service:8008/health
        - http://data-bridge:8001/health
        - http://trading-engine:8007/health
        - http://security-monitor:8020/health
        - http://log-aggregator:8030/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # WebSocket monitoring
  - job_name: 'websocket-monitoring'
    static_configs:
      - targets: ['data-bridge:8001']
    scrape_interval: 30s
    metrics_path: /ws/metrics
    scheme: ws

# Remote write configuration (optional, for long-term storage)
# remote_write:
#   - url: "https://your-remote-prometheus-instance/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Remote read configuration (optional)
# remote_read:
#   - url: "https://your-remote-prometheus-instance/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true