version: '3.8'

services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    restart: unless-stopped
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=3003
      - MONGODB_URI=mongodb://mongo:27017/payment_service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      - payment-network
    volumes:
      - ./logs:/app/logs
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongo:
    image: mongo:6.0-focal
    container_name: payment-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=payment_secure_password
      - MONGO_INITDB_DATABASE=payment_service
    volumes:
      - payment_mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - payment-network
    command: --auth --bind_ip_all
    security_opt:
      - no-new-privileges:true

  redis:
    image: redis:7-alpine
    container_name: payment-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --requirepass payment_redis_password --appendonly yes
    volumes:
      - payment_redis_data:/data
    networks:
      - payment-network
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.core.somaxconn=1024

  nginx:
    image: nginx:alpine
    container_name: payment-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - payment-service
    networks:
      - payment-network
    security_opt:
      - no-new-privileges:true

volumes:
  payment_mongo_data:
    driver: local
  payment_redis_data:
    driver: local

networks:
  payment-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16