service:
  name: user-service
  description: User Service microservice - Enterprise user management with project collaboration and AI workflows
  version: 1.0.0
  environment: ${MICROSERVICE_ENVIRONMENT:development}
  port: ${USER_SERVICE_PORT:8009}
  debug: ${USER_SERVICE_DEBUG:false}
  host: ${USER_SERVICE_HOST:0.0.0.0}
  
cors:
  enabled: ${CORS_ENABLED:true}
  origins:
    - ${CORS_ORIGINS:*}
    
rate_limiting:
  enabled: ${RATE_LIMITING_ENABLED:true}
  requests_per_minute: ${RATE_LIMITING_REQUESTS_PER_MINUTE:1000}

user_management:
  max_users_per_tenant: ${USER_MGMT_MAX_USERS_PER_TENANT:10000}
  default_role: ${USER_MGMT_DEFAULT_ROLE:user}
  password_policy:
    min_length: ${USER_MGMT_PASSWORD_MIN_LENGTH:8}
    require_uppercase: ${USER_MGMT_PASSWORD_REQUIRE_UPPERCASE:true}
    require_lowercase: ${USER_MGMT_PASSWORD_REQUIRE_LOWERCASE:true}
    require_numbers: ${USER_MGMT_PASSWORD_REQUIRE_NUMBERS:true}
    require_special_chars: ${USER_MGMT_PASSWORD_REQUIRE_SPECIAL_CHARS:false}

project_management:
  max_projects_per_user: ${PROJECT_MGMT_MAX_PROJECTS_PER_USER:100}
  default_project_settings:
    ai_features_enabled: ${PROJECT_MGMT_AI_FEATURES_ENABLED:true}
    auto_analysis_enabled: ${PROJECT_MGMT_AUTO_ANALYSIS_ENABLED:true}
    collaboration_enabled: ${PROJECT_MGMT_COLLABORATION_ENABLED:true}
    version_control_enabled: ${PROJECT_MGMT_VERSION_CONTROL_ENABLED:true}
    cost_tracking_enabled: ${PROJECT_MGMT_COST_TRACKING_ENABLED:true}
    analytics_enabled: ${PROJECT_MGMT_ANALYTICS_ENABLED:true}

ai_workflows:
  max_concurrent_workflows: ${AI_WORKFLOWS_MAX_CONCURRENT_WORKFLOWS:50}
  default_timeout_seconds: ${AI_WORKFLOWS_DEFAULT_TIMEOUT_SECONDS:3600}
  cost_tracking_enabled: ${AI_WORKFLOWS_COST_TRACKING_ENABLED:true}
  
caching:
  user_cache_ttl: ${CACHING_USER_CACHE_TTL:3600}        # 1 hour
  profile_cache_ttl: ${CACHING_PROFILE_CACHE_TTL:1800}     # 30 minutes
  ai_preferences_cache_ttl: ${CACHING_AI_PREFERENCES_CACHE_TTL:7200}  # 2 hours
  template_cache_ttl: ${CACHING_TEMPLATE_CACHE_TTL:7200}    # 2 hours
  execution_cache_ttl: ${CACHING_EXECUTION_CACHE_TTL:3600}   # 1 hour
  analytics_cache_ttl: ${CACHING_ANALYTICS_CACHE_TTL:7200}   # 2 hours

collaboration:
  max_collaborators_per_project: ${COLLABORATION_MAX_COLLABORATORS_PER_PROJECT:50}
  roles: ${COLLABORATION_ROLES:owner,admin,contributor,viewer}

authentication:
  jwt_secret: ${JWT_SECRET:}
  jwt_expiry_hours: ${JWT_EXPIRY_HOURS:24}
  refresh_token_expiry_days: ${REFRESH_TOKEN_EXPIRY_DAYS:30}
  enable_2fa: ${ENABLE_2FA:false}
  session_timeout_minutes: ${SESSION_TIMEOUT_MINUTES:480}

performance:
  bulk_operations_batch_size: ${PERFORMANCE_BULK_OPERATIONS_BATCH_SIZE:1000}
  concurrent_requests: ${PERFORMANCE_CONCURRENT_REQUESTS:100}

monitoring:
  health_check_interval_seconds: ${HEALTH_CHECK_INTERVAL:30}
  metrics_enabled: ${METRICS_ENABLED:true}
  performance_tracking: ${PERFORMANCE_TRACKING_ENABLED:true}
  user_activity_tracking: ${MONITORING_USER_ACTIVITY_TRACKING:true}

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:user_service_db}
  user: ${DATABASE_USER:postgres}
  password: ${DATABASE_PASSWORD:}
  
cache:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:6}
  password: ${REDIS_PASSWORD:}
  
logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  enable_user_logging: ${ENABLE_USER_LOGGING:true}
  enable_security_logging: ${ENABLE_SECURITY_LOGGING:true}

security:
  enable_authentication: ${ENABLE_AUTHENTICATION:true}
  api_key_header: ${API_KEY_HEADER:X-API-Key}
  allowed_ips: ${ALLOWED_IPS:}
  enable_audit_logging: ${ENABLE_AUDIT_LOGGING:true}
  enable_rate_limiting: ${SECURITY_RATE_LIMITING:true}
  max_failed_login_attempts: ${SECURITY_MAX_FAILED_LOGIN_ATTEMPTS:5}
  lockout_duration_minutes: ${SECURITY_LOCKOUT_DURATION_MINUTES:30}
  password_history_length: ${SECURITY_PASSWORD_HISTORY_LENGTH:5}
  force_password_change_days: ${SECURITY_FORCE_PASSWORD_CHANGE_DAYS:90}

# Service-to-Service Authentication
service_secrets:
  api_gateway: ${API_GATEWAY_SERVICE_SECRET:}
  database_service: ${DATABASE_SERVICE_SECRET:}
  ai_orchestration: ${AI_ORCHESTRATION_SERVICE_SECRET:}
  ml_processing: ${ML_PROCESSING_SERVICE_SECRET:}
  deep_learning: ${DEEP_LEARNING_SERVICE_SECRET:}
  trading_engine: ${TRADING_ENGINE_SERVICE_SECRET:}
  data_bridge: ${DATA_BRIDGE_SERVICE_SECRET:}

# External AI Services Configuration
external_ai_services:
  openai:
    api_key: ${OPENAI_API_KEY:}
    base_url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    model: ${OPENAI_MODEL:gpt-4}
    timeout_seconds: ${OPENAI_TIMEOUT_SECONDS:30}
  
  anthropic:
    api_key: ${ANTHROPIC_API_KEY:}
    base_url: ${ANTHROPIC_BASE_URL:https://api.anthropic.com}
    model: ${ANTHROPIC_MODEL:claude-3-sonnet-20240229}
    timeout_seconds: ${ANTHROPIC_TIMEOUT_SECONDS:30}
  
  google:
    api_key: ${GOOGLE_AI_API_KEY:}
    project_id: ${GOOGLE_PROJECT_ID:}
    timeout_seconds: ${GOOGLE_AI_TIMEOUT_SECONDS:30}

# Notification Services
notifications:
  email:
    enabled: ${NOTIFICATIONS_EMAIL_ENABLED:true}
    smtp_host: ${SMTP_HOST:}
    smtp_port: ${SMTP_PORT:587}
    smtp_username: ${SMTP_USERNAME:}
    smtp_password: ${SMTP_PASSWORD:}
    use_tls: ${SMTP_USE_TLS:true}
    from_address: ${SMTP_FROM_ADDRESS:noreply@neliti.ai}
  
  slack:
    enabled: ${NOTIFICATIONS_SLACK_ENABLED:false}
    webhook_url: ${SLACK_WEBHOOK_URL:}
    channel: ${SLACK_CHANNEL:#general}
  
  discord:
    enabled: ${NOTIFICATIONS_DISCORD_ENABLED:false}
    webhook_url: ${DISCORD_WEBHOOK_URL:}

# Storage Configuration
storage:
  user_uploads:
    max_file_size_mb: ${STORAGE_MAX_FILE_SIZE_MB:100}
    allowed_extensions: ${STORAGE_ALLOWED_EXTENSIONS:.jpg,.jpeg,.png,.pdf,.doc,.docx,.txt}
    storage_path: ${STORAGE_USER_UPLOADS_PATH:/app/uploads/users}
  
  project_data:
    max_project_size_mb: ${STORAGE_MAX_PROJECT_SIZE_MB:1000}
    storage_path: ${STORAGE_PROJECT_DATA_PATH:/app/uploads/projects}
    backup_enabled: ${STORAGE_BACKUP_ENABLED:true}
    backup_retention_days: ${STORAGE_BACKUP_RETENTION_DAYS:30}
  
  ai_models:
    cache_path: ${STORAGE_AI_MODELS_CACHE_PATH:/app/cache/ai_models}
    max_cache_size_gb: ${STORAGE_AI_MODELS_MAX_CACHE_GB:10}

# Analytics and Metrics
analytics:
  user_behavior_tracking: ${ANALYTICS_USER_BEHAVIOR_TRACKING:true}
  performance_metrics: ${ANALYTICS_PERFORMANCE_METRICS:true}
  error_tracking: ${ANALYTICS_ERROR_TRACKING:true}
  custom_events: ${ANALYTICS_CUSTOM_EVENTS:true}
  retention_days: ${ANALYTICS_RETENTION_DAYS:90}

# Third-party Integrations
integrations:
  google_workspace:
    enabled: ${GOOGLE_WORKSPACE_ENABLED:false}
    client_id: ${GOOGLE_WORKSPACE_CLIENT_ID:}
    client_secret: ${GOOGLE_WORKSPACE_CLIENT_SECRET:}
    domain: ${GOOGLE_WORKSPACE_DOMAIN:}
  
  microsoft_365:
    enabled: ${MICROSOFT_365_ENABLED:false}
    client_id: ${MICROSOFT_365_CLIENT_ID:}
    client_secret: ${MICROSOFT_365_CLIENT_SECRET:}
    tenant_id: ${MICROSOFT_365_TENANT_ID:}
  
  github:
    enabled: ${GITHUB_INTEGRATION_ENABLED:false}
    client_id: ${GITHUB_CLIENT_ID:}
    client_secret: ${GITHUB_CLIENT_SECRET:}
    webhook_secret: ${GITHUB_WEBHOOK_SECRET:}
  
  gitlab:
    enabled: ${GITLAB_INTEGRATION_ENABLED:false}
    client_id: ${GITLAB_CLIENT_ID:}
    client_secret: ${GITLAB_CLIENT_SECRET:}
    instance_url: ${GITLAB_INSTANCE_URL:https://gitlab.com}

# Backup and Recovery
backup:
  enabled: ${BACKUP_ENABLED:true}
  schedule: ${BACKUP_SCHEDULE:0 2 * * *}  # Daily at 2 AM
  retention_days: ${BACKUP_RETENTION_DAYS:30}
  storage_location: ${BACKUP_STORAGE_LOCATION:s3}
  compression_enabled: ${BACKUP_COMPRESSION_ENABLED:true}
  
  s3_config:
    bucket: ${BACKUP_S3_BUCKET:}
    region: ${BACKUP_S3_REGION:us-east-1}
    access_key: ${BACKUP_S3_ACCESS_KEY:}
    secret_key: ${BACKUP_S3_SECRET_KEY:}
    encryption_enabled: ${BACKUP_S3_ENCRYPTION:true}

# Environment-specific configurations
environments:
  development:
    debug: true
    log_level: debug
    enable_2fa: false
    max_users_per_tenant: 1000
  production:
    debug: false
    log_level: info
    enable_2fa: true
    max_users_per_tenant: 10000
  testing:
    debug: true
    log_level: debug
    enable_2fa: false
    max_users_per_tenant: 100