service:
  name: trading-engine
  description: Trading Engine microservice - Order execution, risk management, and strategy execution
  version: 1.0.0
  environment: ${MICROSERVICE_ENVIRONMENT:development}
  port: ${TRADING_ENGINE_PORT:8007}
  debug: ${TRADING_ENGINE_DEBUG:false}
  host: ${TRADING_ENGINE_HOST:0.0.0.0}
  
cors:
  enabled: ${CORS_ENABLED:true}
  origins:
    - ${CORS_ORIGINS:*}
    
rate_limiting:
  enabled: ${RATE_LIMITING_ENABLED:true}
  requests_per_minute: ${RATE_LIMITING_REQUESTS_PER_MINUTE:2000}  # Higher for trading operations

trading:
  max_concurrent_orders: ${TRADING_MAX_CONCURRENT_ORDERS:1000}
  order_timeout_seconds: ${TRADING_ORDER_TIMEOUT_SECONDS:60}
  risk_check_enabled: ${TRADING_RISK_CHECK_ENABLED:true}
  
risk_management:
  max_position_size: ${RISK_MAX_POSITION_SIZE:10.0}
  max_daily_loss_percent: ${RISK_MAX_DAILY_LOSS_PERCENT:5.0}
  max_drawdown_percent: ${RISK_MAX_DRAWDOWN_PERCENT:10.0}
  margin_call_level: ${RISK_MARGIN_CALL_LEVEL:50.0}
  
strategy_execution:
  max_active_strategies: ${STRATEGY_MAX_ACTIVE_STRATEGIES:100}
  backtest_enabled: ${STRATEGY_BACKTEST_ENABLED:true}
  live_trading_enabled: ${STRATEGY_LIVE_TRADING_ENABLED:true}
  
telegram:
  enabled: ${TELEGRAM_ENABLED:true}
  bot_token: ${TELEGRAM_BOT_TOKEN:}
  chat_id: ${TELEGRAM_CHAT_ID:}
  notifications:
    order_executions: ${TELEGRAM_NOTIFY_ORDER_EXECUTIONS:true}
    risk_alerts: ${TELEGRAM_NOTIFY_RISK_ALERTS:true}
    profit_loss_updates: ${TELEGRAM_NOTIFY_PL_UPDATES:true}
    
performance:
  execution_timeout_ms: ${PERFORMANCE_EXECUTION_TIMEOUT_MS:100}
  batch_size: ${PERFORMANCE_BATCH_SIZE:50}
  concurrent_strategies: ${PERFORMANCE_CONCURRENT_STRATEGIES:10}

mt5_bridge:
  url: ${MT5_BRIDGE_URL:ws://localhost:8765}
  timeout_seconds: ${MT5_BRIDGE_TIMEOUT_SECONDS:30}
  reconnect_attempts: ${MT5_BRIDGE_RECONNECT_ATTEMPTS:5}
  heartbeat_interval: ${MT5_BRIDGE_HEARTBEAT_INTERVAL:30}

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:trading_engine_db}
  user: ${DATABASE_USER:postgres}
  password: ${DATABASE_PASSWORD:}
  
cache:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:2}
  password: ${REDIS_PASSWORD:}

# MESSAGE BROKERS CONFIGURATION (Trading Execution Focus)
message_brokers:
  # Redpanda for high-frequency trading operations (PRIMARY)
  redpanda:
    enabled: ${REDPANDA_ENABLED:true}
    bootstrap_servers: ${REDPANDA_BOOTSTRAP_SERVERS:localhost:19092}
    topics:
      ai_decisions: ${REDPANDA_AI_DECISIONS:ai-trading-decisions}
      order_execution: ${REDPANDA_ORDER_EXECUTION:trading-orders}
      position_updates: ${REDPANDA_POSITION_UPDATES:position-updates}
      trade_results: ${REDPANDA_TRADE_RESULTS:trade-execution-results}
    consumer_config:
      group_id: ${REDPANDA_GROUP_ID:trading-engine-consumer}
      auto_offset_reset: ${REDPANDA_AUTO_OFFSET:latest}
      enable_auto_commit: ${REDPANDA_AUTO_COMMIT:true}
      auto_commit_interval_ms: ${REDPANDA_COMMIT_INTERVAL:1000}
    producer_config:
      batch_size: ${REDPANDA_BATCH_SIZE:10}
      compression_type: ${REDPANDA_COMPRESSION:lz4}
      retries: ${REDPANDA_RETRIES:5}
      acks: ${REDPANDA_ACKS:all}
      
  # NATS for trading system events (alerts, status)
  nats:
    enabled: ${NATS_ENABLED:true}
    servers: ${NATS_SERVERS:nats://localhost:4222}
    subjects:
      trading_events: ${NATS_TRADING_EVENTS:trading.engine.*}
      execution_alerts: ${NATS_EXECUTION_ALERTS:trading.alerts.*}
      system_status: ${NATS_SYSTEM_STATUS:trading.status.*}
    jetstream:
      enabled: ${NATS_JETSTREAM_ENABLED:true}
      stream_name: ${NATS_TRADING_STREAM:TRADING_ENGINE}
      storage: ${NATS_STORAGE:file}
      max_age: ${NATS_MAX_AGE:72h}
  
logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  enable_trading_logging: ${ENABLE_TRADING_LOGGING:true}
  enable_risk_logging: ${ENABLE_RISK_LOGGING:true}

monitoring:
  health_check_interval_seconds: ${HEALTH_CHECK_INTERVAL:30}
  metrics_enabled: ${METRICS_ENABLED:true}
  performance_tracking: ${PERFORMANCE_TRACKING_ENABLED:true}
  
security:
  enable_authentication: ${ENABLE_AUTHENTICATION:false}
  api_key_header: ${API_KEY_HEADER:X-API-Key}
  allowed_ips: ${ALLOWED_IPS:}

# Authentication & Service Secrets
authentication:
  enabled: ${AUTH_ENABLED:false}
  jwt_secret: ${JWT_SECRET_KEY:}
  jwt_algorithm: ${JWT_ALGORITHM:HS256}
  token_expire_minutes: ${JWT_TOKEN_EXPIRE_MINUTES:60}

service_secrets:
  api_gateway: ${API_GATEWAY_SERVICE_SECRET:}
  database_service: ${DATABASE_SERVICE_SECRET:}
  ml_processing: ${ML_PROCESSING_SERVICE_SECRET:}
  ai_orchestration: ${AI_ORCHESTRATION_SERVICE_SECRET:}
  deep_learning: ${DEEP_LEARNING_SERVICE_SECRET:}
  data_bridge: ${DATA_BRIDGE_SERVICE_SECRET:}

# Trading Strategies Configuration
trading_strategies:
  enabled: ${TRADING_STRATEGIES_ENABLED:true}
  execution_mode: ${TRADING_STRATEGIES_EXECUTION_MODE:paper}
  
  # Multi-strategy settings
  multi_strategy_enabled: ${TRADING_STRATEGIES_MULTI_STRATEGY:true}
  max_concurrent_strategies: ${TRADING_STRATEGIES_MAX_CONCURRENT:5}
  
  # Strategy allocation
  allocation:
    trend_following: ${TRADING_STRATEGIES_TREND_FOLLOWING_ALLOCATION:0.3}
    mean_reversion: ${TRADING_STRATEGIES_MEAN_REVERSION_ALLOCATION:0.2}
    breakout: ${TRADING_STRATEGIES_BREAKOUT_ALLOCATION:0.2}
    arbitrage: ${TRADING_STRATEGIES_ARBITRAGE_ALLOCATION:0.1}
    ai_driven: ${TRADING_STRATEGIES_AI_DRIVEN_ALLOCATION:0.2}
  
  # Trend Following Strategy
  trend_following:
    enabled: ${TRADING_STRATEGIES_TREND_FOLLOWING:true}
    periods: ${TRADING_STRATEGIES_TREND_PERIODS:20,50,200}
  
  # Mean Reversion Strategy
  mean_reversion:
    enabled: ${TRADING_STRATEGIES_MEAN_REVERSION:true}
    lookback: ${TRADING_STRATEGIES_MEAN_REVERSION_LOOKBACK:14}
    threshold: ${TRADING_STRATEGIES_MEAN_REVERSION_THRESHOLD:2.0}
  
  # Breakout Strategy
  breakout:
    enabled: ${TRADING_STRATEGIES_BREAKOUT:true}
    confirmation_bars: ${TRADING_STRATEGIES_BREAKOUT_CONFIRMATION:3}
    volume_confirmation: ${TRADING_STRATEGIES_BREAKOUT_VOLUME:true}
  
  # AI-Driven Strategy
  ai_driven:
    enabled: ${TRADING_STRATEGIES_AI_DRIVEN:true}
    confidence_threshold: ${TRADING_STRATEGIES_AI_CONFIDENCE_THRESHOLD:0.7}
    consensus_required: ${TRADING_STRATEGIES_AI_CONSENSUS:true}
  
  # Portfolio Management
  portfolio:
    rebalancing_enabled: ${TRADING_STRATEGIES_PORTFOLIO_REBALANCING:true}
    rebalancing_frequency: ${TRADING_STRATEGIES_REBALANCING_FREQUENCY:daily}
    correlation_based_allocation: ${TRADING_STRATEGIES_CORRELATION_ALLOCATION:true}

# Advanced Risk Management
advanced_risk_management:
  enabled: ${RISK_MANAGEMENT_ENABLED:true}
  risk_level: ${RISK_MANAGEMENT_LEVEL:moderate}
  
  # Position Sizing
  position_sizing:
    enabled: ${RISK_MANAGEMENT_POSITION_SIZING:true}
    method: ${RISK_MANAGEMENT_POSITION_SIZING_METHOD:kelly}
    max_position_size: ${RISK_MANAGEMENT_MAX_POSITION_SIZE:0.02}
  
  # Stop Loss Management
  stop_loss:
    enabled: ${RISK_MANAGEMENT_STOP_LOSS:true}
    method: ${RISK_MANAGEMENT_STOP_LOSS_METHOD:atr}
    atr_multiplier: ${RISK_MANAGEMENT_STOP_LOSS_ATR_MULTIPLIER:2.0}
  
  # Take Profit Management
  take_profit:
    enabled: ${RISK_MANAGEMENT_TAKE_PROFIT:true}
    method: ${RISK_MANAGEMENT_TAKE_PROFIT_METHOD:risk_reward}
    risk_reward_ratio: ${RISK_MANAGEMENT_RISK_REWARD_RATIO:2.0}
  
  # Trailing Stop
  trailing_stop:
    enabled: ${RISK_MANAGEMENT_TRAILING_STOP:true}
    distance: ${RISK_MANAGEMENT_TRAILING_STOP_DISTANCE:0.001}
    activation: ${RISK_MANAGEMENT_TRAILING_STOP_ACTIVATION:0.5}
  
  # Drawdown Protection
  drawdown_protection:
    enabled: ${RISK_MANAGEMENT_DRAWDOWN_PROTECTION:true}
    max_daily_drawdown: ${RISK_MANAGEMENT_MAX_DAILY_DRAWDOWN:0.05}
    max_total_drawdown: ${RISK_MANAGEMENT_MAX_TOTAL_DRAWDOWN:0.20}
  
  # Exposure Limits
  exposure_limits:
    enabled: ${RISK_MANAGEMENT_EXPOSURE_LIMITS:true}
    max_currency_exposure: ${RISK_MANAGEMENT_MAX_CURRENCY_EXPOSURE:0.10}
    max_correlation_exposure: ${RISK_MANAGEMENT_MAX_CORRELATION_EXPOSURE:0.15}
  
  # Real-time Monitoring
  realtime_monitoring:
    enabled: ${RISK_MANAGEMENT_REALTIME_MONITORING:true}
    frequency_seconds: ${RISK_MANAGEMENT_MONITORING_FREQUENCY:10}
    emergency_stop_enabled: ${RISK_MANAGEMENT_EMERGENCY_STOP:true}

# Execution Engine Configuration
execution_engine:
  enabled: ${EXECUTION_ENGINE_ENABLED:true}
  execution_delay_ms: ${EXECUTION_ENGINE_DELAY:100}
  
  # Order Management
  order_management:
    enabled: ${EXECUTION_ENGINE_ORDER_MANAGEMENT:true}
    default_order_type: ${EXECUTION_ENGINE_DEFAULT_ORDER_TYPE:market}
    order_timeout_seconds: ${EXECUTION_ENGINE_ORDER_TIMEOUT:30}
  
  # Slippage Control
  slippage_control:
    enabled: ${EXECUTION_ENGINE_SLIPPAGE_CONTROL:true}
    max_slippage: ${EXECUTION_ENGINE_MAX_SLIPPAGE:0.0001}
    tolerance: ${EXECUTION_ENGINE_SLIPPAGE_TOLERANCE:0.5}
  
  # Execution Algorithms
  algorithms:
    enabled: ${EXECUTION_ENGINE_ALGORITHMS:true}
    twap_enabled: ${EXECUTION_ENGINE_TWAP:true}
    vwap_enabled: ${EXECUTION_ENGINE_VWAP:true}
    iceberg_enabled: ${EXECUTION_ENGINE_ICEBERG:true}
  
  # Market Impact
  market_impact:
    minimization_enabled: ${EXECUTION_ENGINE_MARKET_IMPACT_MINIMIZATION:true}
    max_impact: ${EXECUTION_ENGINE_MAX_MARKET_IMPACT:0.0005}
  
  # Partial Fills
  partial_fills:
    enabled: ${EXECUTION_ENGINE_PARTIAL_FILLS:true}
    min_fill_size: ${EXECUTION_ENGINE_MIN_FILL_SIZE:0.01}
  
  # Latency Optimization
  latency_optimization:
    enabled: ${EXECUTION_ENGINE_LATENCY_OPTIMIZATION:true}
    max_latency_ms: ${EXECUTION_ENGINE_MAX_LATENCY:100}
  
  # Broker Integration
  broker_integration:
    enabled: ${EXECUTION_ENGINE_BROKER_INTEGRATION:true}
    primary_broker: ${EXECUTION_ENGINE_PRIMARY_BROKER:FBS-Demo}
    backup_brokers: ${EXECUTION_ENGINE_BACKUP_BROKERS:IC-Markets,Dukascopy}

# Dashboard Configuration
dashboard:
  enabled: ${DASHBOARD_ENABLED:true}
  update_frequency_ms: ${DASHBOARD_UPDATE_FREQUENCY:1000}
  
  # Real-time Data
  realtime_data:
    enabled: ${DASHBOARD_REALTIME_DATA:true}
    refresh_rate_ms: ${DASHBOARD_DATA_REFRESH_RATE:500}
  
  # Performance Metrics
  performance_metrics:
    enabled: ${DASHBOARD_PERFORMANCE_METRICS:true}
    display_metrics: ${DASHBOARD_METRICS_DISPLAY:pnl,drawdown,sharpe,win_rate,trades_today}
  
  # Risk Monitoring
  risk_monitoring:
    display_enabled: ${DASHBOARD_RISK_MONITORING:true}
    alerts_enabled: ${DASHBOARD_RISK_ALERTS:true}
  
  # Portfolio Overview
  portfolio_overview:
    enabled: ${DASHBOARD_PORTFOLIO_OVERVIEW:true}
    allocation_display: ${DASHBOARD_PORTFOLIO_ALLOCATION:true}
  
  # Charts
  charts:
    enabled: ${DASHBOARD_CHARTS:true}
    chart_types: ${DASHBOARD_CHART_TYPES:candlestick,line,volume,indicators}
  
  # Notifications
  notifications:
    enabled: ${DASHBOARD_NOTIFICATIONS:true}
    methods: ${DASHBOARD_NOTIFICATION_METHODS:email,telegram,desktop}
  
  # Export
  export:
    enabled: ${DASHBOARD_EXPORT:true}
    formats: ${DASHBOARD_EXPORT_FORMATS:csv,excel,pdf,json}
  
  # Multi-Broker
  multi_broker:
    display_enabled: ${DASHBOARD_MULTI_BROKER:true}
    comparison_enabled: ${DASHBOARD_BROKER_COMPARISON:true}

# Performance Analytics
performance_analytics:
  enabled: ${PERFORMANCE_ANALYTICS_ENABLED:true}
  update_frequency: ${PERFORMANCE_ANALYTICS_UPDATE_FREQUENCY:hourly}
  
  # Statistical Analysis
  statistical_analysis:
    enabled: ${PERFORMANCE_ANALYTICS_STATISTICAL:true}
    statistics: ${PERFORMANCE_ANALYTICS_STATISTICS:sharpe,sortino,calmar,max_drawdown,var,cvar}
  
  # Backtesting
  backtesting:
    enabled: ${PERFORMANCE_ANALYTICS_BACKTESTING:true}
    period_days: ${PERFORMANCE_ANALYTICS_BACKTESTING_PERIOD:252}
    walk_forward_analysis: ${PERFORMANCE_ANALYTICS_WALK_FORWARD:true}
  
  # Benchmark Comparison
  benchmark_comparison:
    enabled: ${PERFORMANCE_ANALYTICS_BENCHMARK:true}
    instruments: ${PERFORMANCE_ANALYTICS_BENCHMARK_INSTRUMENTS:SPX500,EURUSD,XAUUSD}
  
  # Attribution Analysis
  attribution_analysis:
    enabled: ${PERFORMANCE_ANALYTICS_ATTRIBUTION:true}
    levels: ${PERFORMANCE_ANALYTICS_ATTRIBUTION_LEVELS:strategy,instrument,sector,timeframe}
  
  # Risk-Adjusted Returns
  risk_adjusted_returns:
    enabled: ${PERFORMANCE_ANALYTICS_RISK_ADJUSTED:true}
    risk_free_rate: ${PERFORMANCE_ANALYTICS_RISK_FREE_RATE:0.05}
  
  # Monte Carlo Analysis
  monte_carlo:
    enabled: ${PERFORMANCE_ANALYTICS_MONTE_CARLO:true}
    simulations: ${PERFORMANCE_ANALYTICS_MONTE_CARLO_SIMULATIONS:1000}
  
  # Stress Testing
  stress_testing:
    enabled: ${PERFORMANCE_ANALYTICS_STRESS_TESTING:true}
    scenarios: ${PERFORMANCE_ANALYTICS_STRESS_SCENARIOS:2008_crisis,covid_2020,flash_crash}

# Advanced Telegram Configuration
advanced_telegram:
  enabled: ${TELEGRAM_BOT_ENABLED:false}
  bot_token: ${TELEGRAM_BOT_TOKEN:}
  chat_id: ${TELEGRAM_CHAT_ID:}
  
  # Notification Types
  notifications:
    trade_notifications: ${TELEGRAM_TRADE_NOTIFICATIONS:true}
    risk_alerts: ${TELEGRAM_RISK_ALERTS:true}
    performance_updates: ${TELEGRAM_PERFORMANCE_UPDATES:true}
  
  # Update Settings
  updates:
    frequency: ${TELEGRAM_UPDATE_FREQUENCY:hourly}
    daily_summary: ${TELEGRAM_DAILY_SUMMARY:true}
  
  # Interactive Commands
  interactive:
    commands_enabled: ${TELEGRAM_INTERACTIVE_COMMANDS:true}
    command_whitelist: ${TELEGRAM_COMMAND_WHITELIST:status,performance,positions,stop_trading}
  
  # Security
  security:
    user_authentication: ${TELEGRAM_USER_AUTHENTICATION:true}
    authorized_users: ${TELEGRAM_AUTHORIZED_USERS:}

# Output Execution Settings
output_execution:
  enabled: ${OUTPUT_EXECUTION_ENABLED:true}
  debug_mode: ${OUTPUT_EXECUTION_DEBUG:false}
  
  # Processing Settings
  processing:
    execution_mode: ${OUTPUT_EXECUTION_MODE:paper}
    max_simultaneous_orders: ${OUTPUT_EXECUTION_MAX_SIMULTANEOUS_ORDERS:10}
    order_queue_size: ${OUTPUT_EXECUTION_ORDER_QUEUE_SIZE:1000}
  
  # Performance Monitoring
  performance_monitoring:
    enabled: ${OUTPUT_EXECUTION_PERFORMANCE_MONITORING:true}
    metrics: ${OUTPUT_EXECUTION_PERFORMANCE_METRICS:latency,throughput,success_rate,slippage}
  
  # Database Integration
  database_integration:
    enabled: ${OUTPUT_EXECUTION_DATABASE_ENABLED:true}
    store_orders: ${OUTPUT_EXECUTION_STORE_ORDERS:true}
    store_trades: ${OUTPUT_EXECUTION_STORE_TRADES:true}
    store_performance: ${OUTPUT_EXECUTION_STORE_PERFORMANCE:true}
  
  # Logging
  logging:
    enabled: ${OUTPUT_EXECUTION_LOGGING_ENABLED:true}
    level: ${OUTPUT_EXECUTION_LOGGING_LEVEL:INFO}
    metrics_enabled: ${OUTPUT_EXECUTION_METRICS_ENABLED:true}
  
  # Error Handling
  error_handling:
    enabled: ${OUTPUT_EXECUTION_ERROR_HANDLING:true}
    max_retries: ${OUTPUT_EXECUTION_MAX_RETRIES:3}
    retry_delay_seconds: ${OUTPUT_EXECUTION_RETRY_DELAY:1}
  
  # Health Checks
  health_checks:
    enabled: ${OUTPUT_EXECUTION_HEALTH_CHECK:true}
    interval_seconds: ${OUTPUT_EXECUTION_HEALTH_CHECK_INTERVAL:60}

# Environment-specific configurations
environments:
  development:
    debug: true
    log_level: debug
    live_trading_enabled: false
    risk_max_position_size: 1.0
    trading_strategies:
      execution_mode: paper
    advanced_risk_management:
      position_sizing:
        max_position_size: 0.01
    
  production:
    debug: false
    log_level: info
    live_trading_enabled: true
    risk_max_position_size: 10.0
    trading_strategies:
      execution_mode: live
    advanced_risk_management:
      position_sizing:
        max_position_size: 0.02
        
  testing:
    debug: true
    log_level: debug
    live_trading_enabled: false
    risk_max_position_size: 0.1
    trading_strategies:
      execution_mode: paper
    advanced_risk_management:
      position_sizing:
        max_position_size: 0.001