service:
  name: strategy-optimization
  description: Strategy Optimization microservice - Genetic algorithm-based strategy development and optimization
  version: 1.0.0
  environment: ${MICROSERVICE_ENVIRONMENT:development}
  port: ${STRATEGY_OPTIMIZATION_PORT:8011}
  debug: ${STRATEGY_OPTIMIZATION_DEBUG:false}
  host: ${STRATEGY_OPTIMIZATION_HOST:0.0.0.0}
  
cors:
  enabled: ${CORS_ENABLED:true}
  origins:
    - ${CORS_ORIGINS:*}
    
rate_limiting:
  enabled: ${RATE_LIMITING_ENABLED:true}
  requests_per_minute: ${RATE_LIMITING_REQUESTS_PER_MINUTE:500}

strategy_optimization:
  max_concurrent_optimizations: ${SO_MAX_CONCURRENT_OPTIMIZATIONS:5}
  strategy_cache_size: ${SO_STRATEGY_CACHE_SIZE:1000}
  optimization_timeout_seconds: ${SO_OPTIMIZATION_TIMEOUT_SECONDS:3600}
  backtest_timeout_seconds: ${SO_BACKTEST_TIMEOUT_SECONDS:1800}
  
genetic_algorithm:
  population_size: ${SO_GA_POPULATION_SIZE:100}
  generations: ${SO_GA_GENERATIONS:50}
  mutation_rate: ${SO_GA_MUTATION_RATE:0.1}
  crossover_rate: ${SO_GA_CROSSOVER_RATE:0.8}
  elitism_ratio: ${SO_GA_ELITISM_RATIO:0.1}
  tournament_size: ${SO_GA_TOURNAMENT_SIZE:5}
    
backtesting:
  enabled: ${SO_BACKTESTING_ENABLED:true}
  default_period_days: ${SO_BACKTEST_PERIOD_DAYS:365}
  min_trades_required: ${SO_BACKTEST_MIN_TRADES:50}
  commission_per_trade: ${SO_BACKTEST_COMMISSION:0.001}
  slippage_factor: ${SO_BACKTEST_SLIPPAGE:0.0005}
  
strategy_templates:
  enabled: ${SO_STRATEGY_TEMPLATES_ENABLED:true}
  templates: ${SO_AVAILABLE_TEMPLATES:moving_average,rsi,macd,bollinger_bands,mean_reversion,momentum}
  custom_strategies: ${SO_CUSTOM_STRATEGIES_ENABLED:true}
  strategy_validation: ${SO_STRATEGY_VALIDATION_ENABLED:true}
  
performance:
  gpu_enabled: ${PERFORMANCE_GPU_ENABLED:false}
  max_memory_gb: ${PERFORMANCE_MAX_MEMORY_GB:8}
  concurrent_processes: ${PERFORMANCE_CONCURRENT_PROCESSES:4}
  cache_ttl_seconds: ${PERFORMANCE_CACHE_TTL_SECONDS:1800}

monitoring:
  health_check_interval_seconds: ${HEALTH_CHECK_INTERVAL:30}
  metrics_enabled: ${METRICS_ENABLED:true}
  performance_tracking: ${PERFORMANCE_TRACKING_ENABLED:true}
  optimization_performance_tracking: ${MONITORING_OPTIMIZATION_PERFORMANCE_TRACKING:true}

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:strategy_optimization_db}
  user: ${DATABASE_USER:postgres}
  password: ${DATABASE_PASSWORD:}
  
cache:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:7}
  password: ${REDIS_PASSWORD:}
  
logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  enable_optimization_logging: ${ENABLE_OPTIMIZATION_LOGGING:true}
  enable_strategy_logging: ${ENABLE_STRATEGY_LOGGING:true}

security:
  enable_authentication: ${ENABLE_AUTHENTICATION:false}
  api_key_header: ${API_KEY_HEADER:X-API-Key}
  allowed_ips: ${ALLOWED_IPS:}

# Optimization Configuration
optimization:
  # Multi-Objective Optimization
  multi_objective:
    enabled: ${SO_MULTI_OBJECTIVE_ENABLED:true}
    objectives: ${SO_OPTIMIZATION_OBJECTIVES:profit,risk,drawdown,sharpe_ratio}
    weights: ${SO_OBJECTIVE_WEIGHTS:0.4,0.2,0.2,0.2}
    pareto_optimization: ${SO_PARETO_OPTIMIZATION_ENABLED:true}
    
  # Parameter Optimization
  parameter_optimization:
    enabled: ${SO_PARAMETER_OPTIMIZATION_ENABLED:true}
    optimization_methods: ${SO_OPTIMIZATION_METHODS:genetic_algorithm,particle_swarm,differential_evolution}
    parameter_ranges: ${SO_PARAMETER_RANGES_ENABLED:true}
    adaptive_ranges: ${SO_ADAPTIVE_RANGES_ENABLED:true}
    
  # Strategy Evaluation
  strategy_evaluation:
    enabled: ${SO_STRATEGY_EVALUATION_ENABLED:true}
    evaluation_metrics: ${SO_EVALUATION_METRICS:roi,sharpe_ratio,max_drawdown,win_rate,profit_factor,calmar_ratio}
    risk_adjusted_metrics: ${SO_RISK_ADJUSTED_METRICS_ENABLED:true}
    benchmark_comparison: ${SO_BENCHMARK_COMPARISON_ENABLED:true}
    
  # Convergence Criteria
  convergence:
    max_generations_without_improvement: ${SO_MAX_GENERATIONS_NO_IMPROVEMENT:10}
    fitness_threshold: ${SO_FITNESS_THRESHOLD:0.95}
    population_diversity_threshold: ${SO_DIVERSITY_THRESHOLD:0.1}

# Strategy Configuration
strategy_config:
  # Technical Indicators
  technical_indicators:
    moving_averages:
      enabled: ${SO_MA_ENABLED:true}
      types: ${SO_MA_TYPES:sma,ema,wma,tema}
      periods: ${SO_MA_PERIODS:5,10,20,50,100,200}
      
    oscillators:
      enabled: ${SO_OSCILLATORS_ENABLED:true}
      types: ${SO_OSCILLATOR_TYPES:rsi,stochastic,williams_r,cci}
      periods: ${SO_OSCILLATOR_PERIODS:14,21,28}
      
    trend_indicators:
      enabled: ${SO_TREND_INDICATORS_ENABLED:true}
      types: ${SO_TREND_TYPES:macd,adx,parabolic_sar,ichimoku}
      
    volatility_indicators:
      enabled: ${SO_VOLATILITY_INDICATORS_ENABLED:true}
      types: ${SO_VOLATILITY_TYPES:bollinger_bands,atr,volatility_bands}
      
  # Risk Management
  risk_management:
    enabled: ${SO_RISK_MANAGEMENT_ENABLED:true}
    stop_loss_types: ${SO_STOP_LOSS_TYPES:fixed,trailing,atr_based}
    take_profit_types: ${SO_TAKE_PROFIT_TYPES:fixed,trailing,risk_reward}
    position_sizing: ${SO_POSITION_SIZING_METHODS:fixed,percentage,volatility_based,kelly}
    max_risk_per_trade: ${SO_MAX_RISK_PER_TRADE:0.02}
    max_daily_risk: ${SO_MAX_DAILY_RISK:0.06}
    
  # Entry/Exit Rules
  entry_exit_rules:
    entry_conditions: ${SO_ENTRY_CONDITIONS_ENABLED:true}
    exit_conditions: ${SO_EXIT_CONDITIONS_ENABLED:true}
    filter_conditions: ${SO_FILTER_CONDITIONS_ENABLED:true}
    time_filters: ${SO_TIME_FILTERS_ENABLED:true}

# Backtesting Configuration
backtesting_config:
  # Data Configuration
  data_config:
    timeframes: ${SO_BACKTEST_TIMEFRAMES:1m,5m,15m,1h,4h,1d}
    symbols: ${SO_BACKTEST_SYMBOLS:EURUSD,GBPUSD,USDJPY,AUDUSD,USDCAD}
    data_quality_checks: ${SO_DATA_QUALITY_CHECKS:true}
    
  # Execution Settings
  execution_settings:
    commission_model: ${SO_COMMISSION_MODEL:fixed}
    commission_amount: ${SO_COMMISSION_AMOUNT:0.001}
    slippage_model: ${SO_SLIPPAGE_MODEL:percentage}
    slippage_amount: ${SO_SLIPPAGE_AMOUNT:0.0005}
    
  # Performance Metrics
  performance_metrics:
    return_metrics: ${SO_RETURN_METRICS:total_return,annualized_return,monthly_returns}
    risk_metrics: ${SO_RISK_METRICS:volatility,max_drawdown,var,sharpe_ratio,sortino_ratio}
    trade_metrics: ${SO_TRADE_METRICS:win_rate,profit_factor,avg_trade,max_consecutive_losses}

# Strategy Templates
strategy_templates:
  # Moving Average Strategies
  moving_average:
    enabled: ${SO_MA_STRATEGY_ENABLED:true}
    variants: ${SO_MA_VARIANTS:simple_crossover,dual_crossover,triple_crossover}
    parameters:
      fast_period: ${SO_MA_FAST_PERIOD:10,20}
      slow_period: ${SO_MA_SLOW_PERIOD:50,100}
      
  # RSI Strategies
  rsi:
    enabled: ${SO_RSI_STRATEGY_ENABLED:true}
    variants: ${SO_RSI_VARIANTS:overbought_oversold,divergence,mean_reversion}
    parameters:
      period: ${SO_RSI_PERIOD:14,21}
      overbought_level: ${SO_RSI_OVERBOUGHT:70,80}
      oversold_level: ${SO_RSI_OVERSOLD:20,30}
      
  # MACD Strategies
  macd:
    enabled: ${SO_MACD_STRATEGY_ENABLED:true}
    variants: ${SO_MACD_VARIANTS:signal_crossover,zero_line_crossover,histogram_divergence}
    parameters:
      fast_ema: ${SO_MACD_FAST:12,10}
      slow_ema: ${SO_MACD_SLOW:26,20}
      signal_period: ${SO_MACD_SIGNAL:9,7}
      
  # Bollinger Bands Strategies
  bollinger_bands:
    enabled: ${SO_BB_STRATEGY_ENABLED:true}
    variants: ${SO_BB_VARIANTS:mean_reversion,breakout,squeeze}
    parameters:
      period: ${SO_BB_PERIOD:20,14}
      std_dev: ${SO_BB_STD_DEV:2.0,2.5}

# Authentication & Service Secrets
authentication:
  enabled: ${AUTH_ENABLED:false}
  jwt_secret: ${JWT_SECRET_KEY:}
  jwt_algorithm: ${JWT_ALGORITHM:HS256}
  token_expire_minutes: ${JWT_TOKEN_EXPIRE_MINUTES:60}

service_secrets:
  api_gateway: ${API_GATEWAY_SERVICE_SECRET:}
  database_service: ${DATABASE_SERVICE_SECRET:}
  trading_engine: ${TRADING_ENGINE_SERVICE_SECRET:}
  performance_analytics: ${PERFORMANCE_ANALYTICS_SERVICE_SECRET:}
  ml_processing: ${ML_PROCESSING_SERVICE_SECRET:}
  deep_learning: ${DEEP_LEARNING_SERVICE_SECRET:}

# Environment-specific configurations
environments:
  development:
    debug: true
    log_level: debug
    max_concurrent_optimizations: 2
    genetic_algorithm:
      population_size: 50
      generations: 20
    backtesting:
      default_period_days: 180
      min_trades_required: 25
    strategy_templates:
      moving_average:
        enabled: true
      rsi:
        enabled: true
      macd:
        enabled: false
        
  production:
    debug: false
    log_level: info
    max_concurrent_optimizations: 5
    genetic_algorithm:
      population_size: 100
      generations: 50
    backtesting:
      default_period_days: 365
      min_trades_required: 50
    strategy_templates:
      moving_average:
        enabled: true
      rsi:
        enabled: true
      macd:
        enabled: true
      bollinger_bands:
        enabled: true
        
  testing:
    debug: true
    log_level: debug
    max_concurrent_optimizations: 1
    genetic_algorithm:
      population_size: 20
      generations: 10
    backtesting:
      default_period_days: 90
      min_trades_required: 10
    strategy_templates:
      moving_average:
        enabled: true
      rsi:
        enabled: false