/**
 * ai-orchestrator Configuration
 * Generated by Service Port Coordinator
 */

module.exports = {
    service: {
        name: 'ai-orchestrator',
        port: 8020,
        protocol: 'http',
        description: 'Level 4 Intelligence Orchestrator',
        critical: true
    },

    server: {
        host: process.env.SERVICE_HOST || 'localhost',
        port: process.env.PORT || 8020,
        timeout: 30000
    },

    centralHub: {
        url: process.env.CENTRAL_HUB_URL || 'http://localhost:7000',
        registerOnStart: true,
        heartbeatInterval: 30000
    },

    health: {
        endpoint: '/health',
        interval: 15000
    },

    security: {
        corsEnabled: true,
        rateLimitEnabled: true,
        helmetEnabled: true
    },

    monitoring: {
        metricsEnabled: true,
        loggingEnabled: true,
        performanceTracking: true
    }
};