service:
  name: ml-processing
  description: ML Processing microservice - Machine learning models, technical analysis, and realtime training
  version: 1.0.0
  environment: ${MICROSERVICE_ENVIRONMENT:development}
  port: ${ML_PROCESSING_PORT:8006}
  debug: ${ML_PROCESSING_DEBUG:false}
  host: ${ML_PROCESSING_HOST:0.0.0.0}
  
cors:
  enabled: ${CORS_ENABLED:true}
  origins:
    - ${CORS_ORIGINS:*}
    
rate_limiting:
  enabled: ${RATE_LIMITING_ENABLED:true}
  requests_per_minute: ${RATE_LIMITING_REQUESTS_PER_MINUTE:1500}

machine_learning:
  max_concurrent_models: ${ML_MAX_CONCURRENT_MODELS:20}
  model_cache_size: ${ML_MODEL_CACHE_SIZE:100}
  training_timeout_seconds: ${ML_TRAINING_TIMEOUT_SECONDS:3600}
  inference_timeout_seconds: ${ML_INFERENCE_TIMEOUT_SECONDS:30}
  
technical_analysis:
  indicators: ${TA_INDICATORS:rsi,macd,bollinger_bands,moving_averages,fibonacci}
  timeframes: ${TA_TIMEFRAMES:1m,5m,15m,1h,4h,1d}
    
realtime_training:
  enabled: ${RT_TRAINING_ENABLED:true}
  batch_size: ${RT_TRAINING_BATCH_SIZE:1000}
  update_frequency_minutes: ${RT_TRAINING_UPDATE_FREQUENCY_MINUTES:15}
  min_samples_required: ${RT_TRAINING_MIN_SAMPLES_REQUIRED:10000}
  
model_ensemble:
  max_models: ${ENSEMBLE_MAX_MODELS:10}
  voting_strategy: ${ENSEMBLE_VOTING_STRATEGY:weighted}
  performance_threshold: ${ENSEMBLE_PERFORMANCE_THRESHOLD:0.7}
  
performance:
  gpu_enabled: ${PERFORMANCE_GPU_ENABLED:false}
  max_memory_gb: ${PERFORMANCE_MAX_MEMORY_GB:8}
  concurrent_processes: ${PERFORMANCE_CONCURRENT_PROCESSES:4}
  cache_ttl_seconds: ${PERFORMANCE_CACHE_TTL_SECONDS:1800}

monitoring:
  health_check_interval_seconds: ${HEALTH_CHECK_INTERVAL:30}
  metrics_enabled: ${METRICS_ENABLED:true}
  performance_tracking: ${PERFORMANCE_TRACKING_ENABLED:true}
  model_performance_tracking: ${MONITORING_MODEL_PERFORMANCE_TRACKING:true}

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:ml_processing_db}
  user: ${DATABASE_USER:postgres}
  password: ${DATABASE_PASSWORD:}
  
cache:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:5}
  password: ${REDIS_PASSWORD:}
  
logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  enable_ml_logging: ${ENABLE_ML_LOGGING:true}
  enable_training_logging: ${ENABLE_TRAINING_LOGGING:true}

security:
  enable_authentication: ${ENABLE_AUTHENTICATION:false}
  api_key_header: ${API_KEY_HEADER:X-API-Key}
  allowed_ips: ${ALLOWED_IPS:}

# Model Configuration
models:
  # CatBoost Configuration
  catboost:
    enabled: ${ML_CATBOOST_ENABLED:true}
    iterations: ${ML_CATBOOST_ITERATIONS:1000}
    learning_rate: ${ML_CATBOOST_LEARNING_RATE:0.1}
    depth: ${ML_CATBOOST_DEPTH:6}
    l2_leaf_reg: ${ML_CATBOOST_L2_LEAF_REG:3}
    
  # XGBoost Configuration
  xgboost:
    enabled: ${ML_XGBOOST_ENABLED:true}
    n_estimators: ${ML_XGBOOST_N_ESTIMATORS:100}
    learning_rate: ${ML_XGBOOST_LEARNING_RATE:0.1}
    max_depth: ${ML_XGBOOST_MAX_DEPTH:6}
    subsample: ${ML_XGBOOST_SUBSAMPLE:0.8}
    
  # LightGBM Configuration
  lightgbm:
    enabled: ${ML_LIGHTGBM_ENABLED:true}
    n_estimators: ${ML_LIGHTGBM_N_ESTIMATORS:100}
    learning_rate: ${ML_LIGHTGBM_LEARNING_RATE:0.1}
    max_depth: ${ML_LIGHTGBM_MAX_DEPTH:6}
    num_leaves: ${ML_LIGHTGBM_NUM_LEAVES:31}
    
  # Random Forest Configuration
  random_forest:
    enabled: ${ML_RANDOM_FOREST_ENABLED:true}
    n_estimators: ${ML_RANDOM_FOREST_N_ESTIMATORS:100}
    max_depth: ${ML_RANDOM_FOREST_MAX_DEPTH:10}
    min_samples_split: ${ML_RANDOM_FOREST_MIN_SAMPLES_SPLIT:2}
    
  # Gradient Boost Configuration
  gradient_boost:
    enabled: ${ML_GRADIENT_BOOST_ENABLED:true}
    n_estimators: ${ML_GRADIENT_BOOST_N_ESTIMATORS:100}
    learning_rate: ${ML_GRADIENT_BOOST_LEARNING_RATE:0.1}
    max_depth: ${ML_GRADIENT_BOOST_MAX_DEPTH:3}
    
  # SVM Configuration
  svm:
    enabled: ${ML_SVM_ENABLED:false}
    kernel: ${ML_SVM_KERNEL:rbf}
    c: ${ML_SVM_C:1.0}
    gamma: ${ML_SVM_GAMMA:scale}
    
  # Neural Network Configuration
  neural_network:
    enabled: ${ML_NEURAL_NETWORK_ENABLED:true}
    hidden_layers: ${ML_NEURAL_NETWORK_HIDDEN_LAYERS:100,50}
    activation: ${ML_NEURAL_NETWORK_ACTIVATION:relu}
    solver: ${ML_NEURAL_NETWORK_SOLVER:adam}
    max_iter: ${ML_NEURAL_NETWORK_MAX_ITER:1000}

# Feature Engineering
feature_engineering:
  enabled: ${FEATURE_ENGINEERING_ENABLED:true}
  technical_indicators:
    enabled: ${FEATURE_TECHNICAL_INDICATORS_ENABLED:true}
    indicators: ${FEATURE_TECHNICAL_INDICATORS:rsi,macd,bollinger_bands,moving_averages,fibonacci}
  lag_features:
    enabled: ${FEATURE_LAG_FEATURES_ENABLED:true}
    max_lags: ${FEATURE_MAX_LAGS:10}
  rolling_features:
    enabled: ${FEATURE_ROLLING_FEATURES_ENABLED:true}
    windows: ${FEATURE_ROLLING_WINDOWS:5,10,20,50}
  volatility_features:
    enabled: ${FEATURE_VOLATILITY_FEATURES_ENABLED:true}
    windows: ${FEATURE_VOLATILITY_WINDOWS:10,20,30}

# Data Processing
data_processing:
  preprocessing:
    scaling_method: ${DATA_SCALING_METHOD:standard}
    handle_missing: ${DATA_HANDLE_MISSING:interpolate}
    outlier_detection: ${DATA_OUTLIER_DETECTION:iqr}
  validation:
    train_split: ${DATA_TRAIN_SPLIT:0.7}
    validation_split: ${DATA_VALIDATION_SPLIT:0.15}
    test_split: ${DATA_TEST_SPLIT:0.15}
    time_series_split: ${DATA_TIME_SERIES_SPLIT:true}

# Model Training
training:
  cross_validation:
    enabled: ${TRAINING_CROSS_VALIDATION_ENABLED:true}
    folds: ${TRAINING_CV_FOLDS:5}
    scoring: ${TRAINING_CV_SCORING:neg_mean_squared_error}
  hyperparameter_tuning:
    enabled: ${TRAINING_HYPERPARAMETER_TUNING_ENABLED:true}
    method: ${TRAINING_TUNING_METHOD:grid_search}
    cv_folds: ${TRAINING_TUNING_CV_FOLDS:3}
  early_stopping:
    enabled: ${TRAINING_EARLY_STOPPING_ENABLED:true}
    patience: ${TRAINING_EARLY_STOPPING_PATIENCE:10}
    min_delta: ${TRAINING_EARLY_STOPPING_MIN_DELTA:0.001}

# Model Evaluation
evaluation:
  metrics:
    regression: ${EVALUATION_REGRESSION_METRICS:mse,mae,r2,mape}
    classification: ${EVALUATION_CLASSIFICATION_METRICS:accuracy,precision,recall,f1}
  backtesting:
    enabled: ${EVALUATION_BACKTESTING_ENABLED:true}
    periods: ${EVALUATION_BACKTESTING_PERIODS:30,60,90}
  validation:
    out_of_sample: ${EVALUATION_OUT_OF_SAMPLE:true}
    walk_forward: ${EVALUATION_WALK_FORWARD:true}

# Authentication & Service Secrets
authentication:
  enabled: ${AUTH_ENABLED:false}
  jwt_secret: ${JWT_SECRET_KEY:}
  jwt_algorithm: ${JWT_ALGORITHM:HS256}
  token_expire_minutes: ${JWT_TOKEN_EXPIRE_MINUTES:60}

service_secrets:
  api_gateway: ${API_GATEWAY_SERVICE_SECRET:}
  database_service: ${DATABASE_SERVICE_SECRET:}
  trading_engine: ${TRADING_ENGINE_SERVICE_SECRET:}
  ai_orchestration: ${AI_ORCHESTRATION_SERVICE_SECRET:}
  deep_learning: ${DEEP_LEARNING_SERVICE_SECRET:}
  data_bridge: ${DATA_BRIDGE_SERVICE_SECRET:}

# Environment-specific configurations
environments:
  development:
    debug: true
    log_level: debug
    gpu_enabled: false
    max_concurrent_models: 10
    training:
      cross_validation:
        folds: 3
    models:
      catboost:
        iterations: 100
      xgboost:
        n_estimators: 50
        
  production:
    debug: false
    log_level: info
    gpu_enabled: true
    max_concurrent_models: 20
    training:
      cross_validation:
        folds: 5
      hyperparameter_tuning:
        enabled: true
    models:
      catboost:
        iterations: 1000
      xgboost:
        n_estimators: 200
        
  testing:
    debug: true
    log_level: debug
    gpu_enabled: false
    max_concurrent_models: 5
    training:
      cross_validation:
        folds: 2
      hyperparameter_tuning:
        enabled: false
    models:
      catboost:
        iterations: 50
      xgboost:
        n_estimators: 25