# Prometheus Configuration for AI Trading Platform
# Comprehensive monitoring setup for microservices

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'aitrading'
    environment: 'production'

rule_files:
  - "alerts/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Consul service discovery
  - job_name: 'consul'
    consul_sd_configs:
      - server: 'consul:8500'
        datacenter: 'aitrading-dc1'
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
      - source_labels: [__meta_consul_service_id]
        target_label: instance_id
      - source_labels: [__meta_consul_service_address]
        target_label: __address__
        replacement: '${1}:${__meta_consul_service_port}'

  # Application Services
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: 'api-gateway'

  - job_name: 'central-hub'
    static_configs:
      - targets: ['central-hub:8003']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: 'central-hub'

  - job_name: 'database-service'
    static_configs:
      - targets: ['database-service:8005']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: 'database-service'

  - job_name: 'data-bridge'
    static_configs:
      - targets: ['data-bridge:8007']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    relabel_configs:
      - target_label: service
        replacement: 'data-bridge'

  # Infrastructure Services
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  - job_name: 'consul-services'
    static_configs:
      - targets: ['consul:8500']
    scrape_interval: 30s
    metrics_path: /v1/agent/metrics
    params:
      format: ['prometheus']

  # Node Exporter (if deployed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Docker Engine metrics (if available)
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics (if available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Custom business metrics
  - job_name: 'trading-metrics'
    consul_sd_configs:
      - server: 'consul:8500'
        services: ['trading-analytics']
    scrape_interval: 10s
    metrics_path: /api/metrics
    relabel_configs:
      - source_labels: [__meta_consul_service]
        target_label: job
        replacement: '${1}'

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     write_relabel_configs:
#       - source_labels: [__name__]
#         regex: 'trading_.*'
#         action: keep

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 50GB
    wal-compression: true