version: '3.8'

# Forex & Gold Trading Platform - Development Environment
# Optimized for development with hot-reload and debugging

networks:
  forexgold-dev:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16

volumes:
  redis_data_dev:
  postgres_data_dev:
  mongodb_data_dev:

services:
  # Development Database
  postgres-dev:
    image: postgres:15-alpine
    container_name: forexgold-postgres-dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database-service/migrations:/docker-entrypoint-initdb.d:ro
    networks:
      - forexgold-dev
    environment:
      - POSTGRES_DB=forexgold_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aitrading2024
      - POSTGRES_MULTIPLE_DATABASES=forex,gold,analytics,payments,logs
      - TZ=Asia/Jakarta
    restart: unless-stopped

  # Development Redis
  redis-dev:
    image: redis:7-alpine
    container_name: forexgold-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis_data_dev:/data
    networks:
      - forexgold-dev
    environment:
      - REDIS_PASSWORD=aitrading2024
      - TZ=Asia/Jakarta
    restart: unless-stopped

  # Development MongoDB
  mongodb-dev:
    image: mongo:7.0
    container_name: forexgold-mongodb-dev
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data_dev:/data/db
    networks:
      - forexgold-dev
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=aitrading2024
      - MONGO_INITDB_DATABASE=forex_gold_logs
      - TZ=Asia/Jakarta
    restart: unless-stopped

  # API Gateway (Development with hot-reload)
  api-gateway-dev:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
      target: development
    container_name: forexgold-gateway-dev
    ports:
      - "8000:8000"
      - "8001:8001"
      - "9229:9229" # Debug port
    volumes:
      - ./api-gateway:/app
      - /app/node_modules
    networks:
      - forexgold-dev
    environment:
      - NODE_ENV=development
      - PORT=8000
      - ADMIN_PORT=8001
      - LOG_LEVEL=debug
      - TZ=Asia/Jakarta
      - TRADING_MODE=FOREX_GOLD
      - BASE_CURRENCY=IDR
      - LOCALE=id_ID
      - HIGH_FREQUENCY_ENABLED=true
      - POSTGRES_HOST=postgres-dev
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
    depends_on:
      - postgres-dev
      - redis-dev
    command: npm run dev
    restart: unless-stopped

  # Development Tools
  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: forexgold-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - forexgold-dev
    restart: unless-stopped

  # Redis Commander (Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: forexgold-redis-gui
    ports:
      - "8081:8081"
    networks:
      - forexgold-dev
    environment:
      - REDIS_HOSTS=local:redis-dev:6379:0:aitrading2024
    depends_on:
      - redis-dev
    restart: unless-stopped

  # MongoDB Express (MongoDB GUI)
  mongo-express:
    image: mongo-express:latest
    container_name: forexgold-mongo-gui
    ports:
      - "8082:8081"
    networks:
      - forexgold-dev
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=aitrading2024
      - ME_CONFIG_MONGODB_SERVER=mongodb-dev
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongodb-dev
    restart: unless-stopped