service:
  name: performance-analytics
  description: Performance Analytics microservice - Trade outcome analysis and performance reporting
  version: 1.0.0
  environment: ${MICROSERVICE_ENVIRONMENT:development}
  port: ${PERFORMANCE_ANALYTICS_PORT:8010}
  debug: ${PERFORMANCE_ANALYTICS_DEBUG:false}
  host: ${PERFORMANCE_ANALYTICS_HOST:0.0.0.0}
  
cors:
  enabled: ${CORS_ENABLED:true}
  origins:
    - ${CORS_ORIGINS:*}
    
rate_limiting:
  enabled: ${RATE_LIMITING_ENABLED:true}
  requests_per_minute: ${RATE_LIMITING_REQUESTS_PER_MINUTE:1000}

performance_analytics:
  max_concurrent_reports: ${PA_MAX_CONCURRENT_REPORTS:10}
  report_cache_size: ${PA_REPORT_CACHE_SIZE:500}
  analysis_timeout_seconds: ${PA_ANALYSIS_TIMEOUT_SECONDS:300}
  report_generation_timeout_seconds: ${PA_REPORT_TIMEOUT_SECONDS:600}
  
trade_analysis:
  metrics: ${PA_TRADE_METRICS:roi,sharpe_ratio,max_drawdown,win_rate,profit_factor}
  timeframes: ${PA_ANALYSIS_TIMEFRAMES:1d,7d,30d,90d,365d}
  benchmark_comparisons: ${PA_BENCHMARK_COMPARISONS:sp500,nasdaq,btc}
    
reporting:
  enabled: ${PA_REPORTING_ENABLED:true}
  formats: ${PA_REPORT_FORMATS:json,pdf,excel}
  auto_generation_interval_hours: ${PA_AUTO_REPORT_INTERVAL:24}
  retention_days: ${PA_REPORT_RETENTION_DAYS:90}
  
ai_insights:
  enabled: ${PA_AI_INSIGHTS_ENABLED:true}
  model_comparison: ${PA_MODEL_COMPARISON_ENABLED:true}
  performance_prediction: ${PA_PERFORMANCE_PREDICTION_ENABLED:true}
  recommendation_engine: ${PA_RECOMMENDATION_ENGINE_ENABLED:true}
  
performance:
  gpu_enabled: ${PERFORMANCE_GPU_ENABLED:false}
  max_memory_gb: ${PERFORMANCE_MAX_MEMORY_GB:4}
  concurrent_processes: ${PERFORMANCE_CONCURRENT_PROCESSES:2}
  cache_ttl_seconds: ${PERFORMANCE_CACHE_TTL_SECONDS:900}

monitoring:
  health_check_interval_seconds: ${HEALTH_CHECK_INTERVAL:30}
  metrics_enabled: ${METRICS_ENABLED:true}
  performance_tracking: ${PERFORMANCE_TRACKING_ENABLED:true}
  analytics_performance_tracking: ${MONITORING_ANALYTICS_PERFORMANCE_TRACKING:true}

database:
  host: ${DATABASE_HOST:localhost}
  port: ${DATABASE_PORT:5432}
  name: ${DATABASE_NAME:performance_analytics_db}
  user: ${DATABASE_USER:postgres}
  password: ${DATABASE_PASSWORD:}
  
cache:
  host: ${REDIS_HOST:localhost}
  port: ${REDIS_PORT:6379}
  db: ${REDIS_DB:6}
  password: ${REDIS_PASSWORD:}
  
logging:
  level: ${LOG_LEVEL:INFO}
  format: ${LOG_FORMAT:json}
  enable_analytics_logging: ${ENABLE_ANALYTICS_LOGGING:true}
  enable_performance_logging: ${ENABLE_PERFORMANCE_LOGGING:true}

security:
  enable_authentication: ${ENABLE_AUTHENTICATION:false}
  api_key_header: ${API_KEY_HEADER:X-API-Key}
  allowed_ips: ${ALLOWED_IPS:}

# Analytics Configuration
analytics:
  # Performance Metrics Configuration
  performance_metrics:
    enabled: ${PA_PERFORMANCE_METRICS_ENABLED:true}
    roi_calculation: ${PA_ROI_CALCULATION:time_weighted}
    sharpe_ratio_risk_free_rate: ${PA_SHARPE_RISK_FREE_RATE:0.02}
    volatility_window_days: ${PA_VOLATILITY_WINDOW:30}
    max_drawdown_calculation: ${PA_MAX_DRAWDOWN_CALC:peak_to_trough}
    
  # Risk Analytics Configuration
  risk_analytics:
    enabled: ${PA_RISK_ANALYTICS_ENABLED:true}
    var_confidence_level: ${PA_VAR_CONFIDENCE:0.95}
    var_window_days: ${PA_VAR_WINDOW:252}
    beta_benchmark: ${PA_BETA_BENCHMARK:sp500}
    correlation_analysis: ${PA_CORRELATION_ANALYSIS_ENABLED:true}
    
  # Strategy Comparison Configuration
  strategy_comparison:
    enabled: ${PA_STRATEGY_COMPARISON_ENABLED:true}
    benchmark_strategies: ${PA_BENCHMARK_STRATEGIES:buy_and_hold,moving_average,rsi_strategy}
    statistical_tests: ${PA_STATISTICAL_TESTS:t_test,mann_whitney,sharpe_test}
    comparison_periods: ${PA_COMPARISON_PERIODS:30,60,90,180,365}
    
  # Model Performance Analysis
  model_performance:
    enabled: ${PA_MODEL_PERFORMANCE_ENABLED:true}
    ml_model_tracking: ${PA_ML_MODEL_TRACKING:true}
    dl_model_tracking: ${PA_DL_MODEL_TRACKING:true}
    ai_model_tracking: ${PA_AI_MODEL_TRACKING:true}
    prediction_accuracy_metrics: ${PA_PREDICTION_METRICS:mae,mse,mape,accuracy}

# Reporting Configuration
reporting_config:
  # Report Types
  report_types:
    daily_performance: ${PA_DAILY_REPORTS_ENABLED:true}
    weekly_summary: ${PA_WEEKLY_REPORTS_ENABLED:true}
    monthly_analysis: ${PA_MONTHLY_REPORTS_ENABLED:true}
    quarterly_review: ${PA_QUARTERLY_REPORTS_ENABLED:true}
    annual_report: ${PA_ANNUAL_REPORTS_ENABLED:true}
    
  # Report Content
  report_content:
    include_charts: ${PA_REPORT_INCLUDE_CHARTS:true}
    include_recommendations: ${PA_REPORT_INCLUDE_RECOMMENDATIONS:true}
    include_risk_analysis: ${PA_REPORT_INCLUDE_RISK:true}
    include_model_comparison: ${PA_REPORT_INCLUDE_MODEL_COMPARISON:true}
    include_benchmark_comparison: ${PA_REPORT_INCLUDE_BENCHMARK:true}
    
  # Export Configuration
  export_config:
    pdf_enabled: ${PA_PDF_EXPORT_ENABLED:true}
    excel_enabled: ${PA_EXCEL_EXPORT_ENABLED:true}
    csv_enabled: ${PA_CSV_EXPORT_ENABLED:true}
    json_enabled: ${PA_JSON_EXPORT_ENABLED:true}

# Data Processing
data_processing:
  preprocessing:
    data_cleaning: ${PA_DATA_CLEANING_ENABLED:true}
    outlier_detection: ${PA_OUTLIER_DETECTION:iqr}
    missing_data_handling: ${PA_MISSING_DATA_HANDLING:interpolate}
  aggregation:
    time_aggregation: ${PA_TIME_AGGREGATION:1h,4h,1d,1w,1m}
    performance_aggregation: ${PA_PERFORMANCE_AGGREGATION:daily,weekly,monthly}
  validation:
    data_quality_checks: ${PA_DATA_QUALITY_CHECKS:true}
    consistency_validation: ${PA_CONSISTENCY_VALIDATION:true}

# AI Integration
ai_integration:
  # Performance Prediction
  performance_prediction:
    enabled: ${PA_AI_PERFORMANCE_PREDICTION:true}
    prediction_horizon_days: ${PA_PREDICTION_HORIZON:30}
    confidence_threshold: ${PA_AI_CONFIDENCE_THRESHOLD:0.75}
    
  # Recommendation Engine
  recommendation_engine:
    enabled: ${PA_AI_RECOMMENDATIONS:true}
    recommendation_types: ${PA_RECOMMENDATION_TYPES:strategy_optimization,risk_management,portfolio_allocation}
    update_frequency_hours: ${PA_RECOMMENDATION_UPDATE_FREQUENCY:24}
    
  # Anomaly Detection
  anomaly_detection:
    enabled: ${PA_ANOMALY_DETECTION:true}
    detection_methods: ${PA_ANOMALY_METHODS:statistical,ml_based,threshold_based}
    alert_threshold: ${PA_ANOMALY_ALERT_THRESHOLD:2.5}

# Authentication & Service Secrets
authentication:
  enabled: ${AUTH_ENABLED:false}
  jwt_secret: ${JWT_SECRET_KEY:}
  jwt_algorithm: ${JWT_ALGORITHM:HS256}
  token_expire_minutes: ${JWT_TOKEN_EXPIRE_MINUTES:60}

service_secrets:
  api_gateway: ${API_GATEWAY_SERVICE_SECRET:}
  database_service: ${DATABASE_SERVICE_SECRET:}
  trading_engine: ${TRADING_ENGINE_SERVICE_SECRET:}
  ml_processing: ${ML_PROCESSING_SERVICE_SECRET:}
  deep_learning: ${DEEP_LEARNING_SERVICE_SECRET:}
  ai_orchestration: ${AI_ORCHESTRATION_SERVICE_SECRET:}

# Environment-specific configurations
environments:
  development:
    debug: true
    log_level: debug
    max_concurrent_reports: 5
    analytics:
      performance_metrics:
        volatility_window_days: 15
      risk_analytics:
        var_window_days: 126
    reporting_config:
      report_types:
        daily_performance: true
        weekly_summary: false
        monthly_analysis: false
        
  production:
    debug: false
    log_level: info
    max_concurrent_reports: 10
    analytics:
      performance_metrics:
        volatility_window_days: 30
      risk_analytics:
        var_window_days: 252
    reporting_config:
      report_types:
        daily_performance: true
        weekly_summary: true
        monthly_analysis: true
        quarterly_review: true
        annual_report: true
        
  testing:
    debug: true
    log_level: debug
    max_concurrent_reports: 2
    analytics:
      performance_metrics:
        volatility_window_days: 10
      risk_analytics:
        var_window_days: 60
    reporting_config:
      report_types:
        daily_performance: true
        weekly_summary: false
        monthly_analysis: false