# Production Security Override
# Removes exposed database ports and adds enhanced security

version: '3.8'

services:
  # Remove database port exposure for production security
  postgresql:
    ports: []  # Remove host port mapping - internal access only
    environment:
      - POSTGRES_DB=neliti_production
      - POSTGRES_USER=neliti_prod_user
      - POSTGRES_PASSWORD=neliti_secure_production_password_2024

  clickhouse:
    ports: []  # Remove host port mapping - internal access only
    environment:
      - CLICKHOUSE_DB=trading_production_data
      - CLICKHOUSE_USER=neliti_prod_user
      - CLICKHOUSE_PASSWORD=clickhouse_secure_production_password_2024

  dragonflydb:
    ports: []  # Remove host port mapping - internal access only
    command: >
      dragonfly
      --requirepass=dragonfly_secure_production_password_2024
      --maxmemory=4gb
      --cache_mode=true
      --proactor_threads=4
      --cluster_mode=emulated
      --default_lua_flags=allow-undeclared-keys
      --tcp_keepalive=300

  weaviate:
    ports: []  # Remove host port mapping - internal access only
    environment:
      - QUERY_DEFAULTS_LIMIT=25
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=false
      - AUTHENTICATION_APIKEY_ENABLED=true
      - AUTHENTICATION_APIKEY_ALLOWED_KEYS=weaviate_secure_production_api_key_2024
      - AUTHENTICATION_APIKEY_USERS=neliti_prod_user
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - DEFAULT_VECTORIZER_MODULE=text2vec-openai
      - ENABLE_MODULES=text2vec-openai,generative-openai,qna-openai
      - CLUSTER_HOSTNAME=node1

  arangodb:
    ports: []  # Remove host port mapping - internal access only
    environment:
      - ARANGO_ROOT_PASSWORD=arangodb_secure_production_password_2024
      - ARANGO_NO_AUTH=false

  # Message Broker - Production Configuration
  nats:
    ports: []  # Remove host port mapping - internal access only
    command: >
      --jetstream
      --store_dir=/data
      --max_memory_store=4GB
      --max_file_store=50GB
      --http_port=8222
      --cluster_name=neliti-prod-cluster
      --cluster_listen=0.0.0.0:6222