# AI Trading Platform - Production Environment
# Optimized for performance and security

version: '3.8'

secrets:
  openai_api_key:
    external: true
  deepseek_api_key:
    external: true
  google_ai_api_key:
    external: true
  handit_ai_api_key:
    external: true
  mt5_login:
    external: true
  mt5_password:
    external: true
  jwt_secret_key:
    external: true

services:
  api-gateway:
    extends:
      file: docker-compose.yml
      service: api-gateway
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - CORS_ENABLED=true
      - CORS_ORIGINS=https://neliti-trading.com,https://api.neliti-trading.com,https://admin.neliti-trading.com
      - AUTH_ENABLED=true
      - LOG_LEVEL=INFO
      - DEBUG=false
    secrets:
      - jwt_secret_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  data-bridge:
    extends:
      file: docker-compose.yml
      service: data-bridge
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - CORS_ENABLED=true
      - CORS_ORIGINS=https://neliti-trading.com,https://api.neliti-trading.com,https://admin.neliti-trading.com
      - LOG_LEVEL=INFO
      - DEBUG=false
      - RATE_LIMITING_ENABLED=true
      - RATE_LIMITING_REQUESTS_PER_MINUTE=1000
      - MT5_SERVER=MetaQuotes-Live
    secrets:
      - mt5_login
      - mt5_password
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  trading-engine:
    extends:
      file: docker-compose.yml
      service: trading-engine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 4G
        reservations:
          cpus: '2'
          memory: 2G

  ml-processing:
    extends:
      file: docker-compose.yml
      service: ml-processing
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8006/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

  deep-learning:
    extends:
      file: docker-compose.yml
      service: deep-learning
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - DEBUG=false
      - CORS_ENABLED=true
      - CORS_ORIGINS=https://neliti-trading.com,https://api.neliti-trading.com,https://admin.neliti-trading.com
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    runtime: nvidia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 16G
        reservations:
          cpus: '4'
          memory: 8G
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ai-orchestration:
    extends:
      file: docker-compose.yml
      service: ai-orchestration
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - DEBUG=false
      - CORS_ENABLED=true
      - CORS_ORIGINS=https://neliti-trading.com,https://api.neliti-trading.com,https://admin.neliti-trading.com
    secrets:
      - openai_api_key
      - handit_ai_api_key
      - deepseek_api_key
      - google_ai_api_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G
        reservations:
          cpus: '2'
          memory: 4G

  ai-provider:
    extends:
      file: docker-compose.yml
      service: ai-provider
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - MICROSERVICE_ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - DEBUG=false
      - CORS_ENABLED=true
      - CORS_ORIGINS=https://neliti-trading.com,https://api.neliti-trading.com,https://admin.neliti-trading.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 6G
        reservations:
          cpus: '1.5'
          memory: 3G

  database-service:
    extends:
      file: docker-compose.yml
      service: database-service
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - POSTGRES_USER=neliti_prod_user
      - POSTGRES_PASSWORD=neliti_secure_production_password_2024
      - POSTGRES_DB=neliti_production
      - CLICKHOUSE_USER=neliti_prod_user
      - CLICKHOUSE_PASSWORD=clickhouse_secure_production_password_2024
      - CLICKHOUSE_DB=trading_production_data
      - LOG_LEVEL=INFO
      - DEBUG=false
      - CORS_ENABLED=true
      - CORS_ORIGINS=https://neliti-trading.com,https://api.neliti-trading.com,https://admin.neliti-trading.com
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '1'
          memory: 2G

  user-service:
    extends:
      file: docker-compose.yml
      service: user-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8009/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G